# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Ayman Aboghonim # the website title
first_name: Ayman
middle_name: 
last_name: Aboghonim
contact_note: >
  Feel free to reach out for collaborations, consultations, or discussions about AI/ML engineering and developer advocacy.
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Personal blog sharing AI/ML insights, career development tips, and practical developer resources. 
  From prompt engineering to professional growth strategies. AI/ML Engineer & Developer Advocate 
  passionate about making complex technology accessible and actionable.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: AI, ML, machine learning, artificial intelligence, developer advocacy, prompt engineering, career development, tech solutions
lang: en # the language of your site
icon: 🤖 # the emoji used as the favicon

url: https://aymanaboghonim.github.io # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: true # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer
back_to_top: true # set to false to disable the back to top button

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# repo color theme
repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed # https://github.com/ryo-ma/github-profile-trophy

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: false

# Dimensions
max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
serve_og_meta: true # Include Open Graph meta tags in the HTML head
serve_schema_org: true # Include Schema.org in the HTML head
og_image: /assets/img/profile.jpg # The site-wide Open Graph preview image

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics: # Add your Google Analytics measurement ID here
cronitor_analytics: # cronitor RUM analytics site ID
pirsch_analytics: # your Pirsch analytics site ID
openpanel_analytics: # your Openpanel analytics client ID

google_site_verification: # your google-site-verification ID
bing_site_verification: # your bing-site-verification ID

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: Tech Insights Blog
blog_description: AI/ML engineering insights, career development, and practical tech solutions
permalink: /blog/:year/:title/
lsi: false

# Pagination
pagination:
  enabled: true
  per_page: 10
  permalink: '/blog/page:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

related_blog_posts:
  enabled: true
  max_related: 5
  min_common_tags: 1

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_scrollable: true # adds a vertical scroll bar if there are more than 3 news items
news_limit: 5 # leave blank to include all the news in the `_news` folder

latest_posts:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 new posts items
  limit: 3 # leave blank to include all the blog posts

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor

# Plug-ins
plugins:
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-responsive-image
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Aboghonim]
  first_name: [Ayman]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

# Display different badges withs stats for your repositories
enable_project_categories: true
repository_categories:
  - name: AI/ML Projects
    include: ai-ml
  - name: Developer Tools
    include: dev-tools
  - name: Open Source
    include: open-source

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: aymanaboghonim
twitter_username: # your Twitter handle
mastodon_username: # your mastodon instance+username in the format instance.tld/@username
linkedin_username: ayman-aboghonim
medium_username: # your Medium username
scholar_userid: # your Google Scholar ID
semanticscholar_id: # your Semantic Scholar ID
whatsapp_number: # your WhatsApp number (full phone number in international format. Omit any zeroes, brackets, or dashes when adding the phone number in international format.)
orcid_id: # your ORCID ID
research_gate_profile: # your profile on ResearchGate
scopus_id: # your profile on Scopus
blogger_url: # your blogger URL
work_url: # work page URL
keybase_username: # your keybase user name
wikidata_id: # your wikidata id
wikipedia_id: # your wikipedia id (Case sensitive)
dblp_url: # your DBLP profile url
stackoverflow_id: # your stackoverflow id
kaggle_id: # your kaggle id
lastfm_id: # your lastfm id
spotify_id: # your spotify id
pinterest_id: # your pinterest id
unsplash_id: # your unsplash id
instagram_id: # your instagram id
facebook_id: # your facebook id
youtube_id: # your youtube channel id (youtube.com/channel/your-channel-id)
discord_id: # your discord id (18-digit unique numerical identifier)
zotero_username: # your zotero username
wechat_qr: # filename of your wechat qr-code saved as an image (e.g., wechat-qr.png if saved to assets/img/wechat-qr.png)

contact_note: # You can even add a little note about which of these is the best way to reach you.

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

# For Google Analytics 4, see https://support.google.com/analytics/answer/10447272
google_analytics: # your Google Analytics measurement ID (format: G-XXXXXXXXXX)

# For Google Search Console, see https://support.google.com/webmasters/answer/9008080
google_site_verification: # your google-site-verification ID (Google Search Console)

# For Bing Webmaster Tools, see https://www.bing.com/webmasters/help/add-and-verify-site-12184f8b
bing_site_verification: # your bing-site-verification ID (Bing Webmaster Tools)

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------

jquery: false # load the jQuery library

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

bootstrap:
  version: "4.6.1"
  integrity:
    css: "sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
    js: "sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2"

fontawesome:
  version: "6.4.0"
  integrity: "sha256-HtsXJanqjKTc8vVQjO4YMhiqFoXkfBsjBWcX91T1jr8="

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="

jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="

mathjax:
  version: "3.2.0"

masonry:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="

mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="

medium_zoom:
  version: "1.0.8"
  integrity: "sha256-7PhEpEWEW0XXQ0k6kQrPKwuoIomz8R8IYyuU1Qew4P8="

lottie:
  version: "5.12.2"
